# Use an official Apache HTTP Server image to serve the site
FROM httpd:alpine

COPY ./public/ /usr/local/apache2/htdocs/

# Expose port 80 to access the site
EXPOSE 80

# Start the Apache server
CMD ["httpd-foreground"]
